version: '2'
volumes:
  orderer.demo.com:
  orderer2.example.com:
  orderer3.example.com:
  orderer4.example.com:
  orderer5.example.com:
services:
  orderer.demo.com:
    container_name: orderer.demo.com
    dns_search: .
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    networks:
      order-raft:
    #        ipv4_address: 172.80.0.10
    volumes:
      - ../artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer.demo.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer.demo.com/tls/:/var/hyperledger/orderer/tls
    #      - orderer.demo.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer2.demo.com:
    container_name: orderer2.demo.com
    dns_search: .
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    networks:
      order-raft:
    #        ipv4_address: 172.80.0.12
    volumes:
      - ../artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer2.demo.com/msp/:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer2.demo.com/tls/:/var/hyperledger/orderer/tls
    #      - orderer2.demo.com:/var/hyperledger/production/orderer
    ports:
      - 7070:7050
  orderer3.demo.com:
    dns_search: .
    container_name: orderer3.demo.com
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    networks:
      order-raft:
    #        ipv4_address: 172.80.0.13
    volumes:
      - ../artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer3.demo.com/msp/:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer3.demo.com/tls/:/var/hyperledger/orderer/tls
    #      - orderer3.demo.com:/var/hyperledger/production/orderer
    ports:
      - 7080:7050
  orderer4.demo.com:
    dns_search: .
    container_name: orderer4.demo.com
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    networks:
      order-raft:
    #        ipv4_address: 172.80.0.14
    volumes:
      - ../artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer4.demo.com/msp/:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer4.demo.com/tls/:/var/hyperledger/orderer/tls
    #      - orderer4.demo.com:/var/hyperledger/production/orderer
    ports:
      - 7090:7050
  orderer5.demo.com:
    dns_search: .
    container_name: orderer5.demo.com
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    networks:
      order-raft:
    #        ipv4_address: 172.80.0.11
    volumes:
      - ../artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer5.demo.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/demo.com/orderers/orderer5.demo.com/tls/:/var/hyperledger/orderer/tls
    #      - orderer5.demo.com:/var/hyperledger/production/orderer
    ports:
      - 7060:7050



  Org1Peer0:
    dns_search: .
    container_name: peer0.org1.demo.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    networks:
      order-raft:
    environment:
      - CORE_PEER_ID=peer0.org1.demo.com
      - CORE_PEER_ADDRESS=peer0.org1.demo.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.demo.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.demo.com:8061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.demo.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
    ports:
      - "8051:8051"
    #      - "8052:8052"
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org1.demo.com/peers/peer0.org1.demo.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.demo.com/peers/peer0.org1.demo.com/tls:/etc/hyperledger/fabric/tls
    #      - ../crypto-config/peerOrganizations/demo.com/tlsca:/etc/hyperledger/orgs/peer0.org1.demo.com/tlsca


  Org1Peer1:
    dns_search: .
    container_name: peer1.org1.demo.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    networks:
      order-raft:
    environment:
      - CORE_PEER_ID=peer1.org1.demo.com
      - CORE_PEER_ADDRESS=peer1.org1.demo.com:8061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8061
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.demo.com:8062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.demo.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.demo.com:8061
      - CORE_PEER_LOCALMSPID=Org1MSP
    ports:
      - "8061:8061"
    #      - "8062:8062"
    volumes:
      - /var/run/:/var/run/
      - ../crypto-config/peerOrganizations/org1.demo.com/peers/peer1.org1.demo.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.demo.com/peers/peer1.org1.demo.com/tls:/etc/hyperledger/fabric/tls

  Org2Peer0:
    dns_search: .
    container_name: peer0.org2.demo.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    networks:
      order-raft:
    environment:
      - CORE_PEER_ID=peer0.org2.demo.com
      - CORE_PEER_ADDRESS=peer0.org2.demo.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.demo.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.demo.com:9061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.demo.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    ports:
      - "9051:9051"
    #      - "9052:9052"
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org2.demo.com/peers/peer0.org2.demo.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org2.demo.com/peers/peer0.org2.demo.com/tls:/etc/hyperledger/fabric/tls
    #      - ../crypto-config/peerOrganizations/demo.com/tlsca:/etc/hyperledger/orgs/peer0.org1.demo.com/tlsca


  Org2Peer1:
    dns_search: .
    container_name: peer1.org2.demo.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    networks:
      order-raft:
    environment:
      - CORE_PEER_ID=peer1.org2.demo.com
      - CORE_PEER_ADDRESS=peer1.org2.demo.com:9061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9061
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.demo.com:9062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.demo.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.demo.com:9061
      - CORE_PEER_LOCALMSPID=Org2MSP
    ports:
      - "9061:9061"
    #      - "9062:9062"
    volumes:
      - /var/run/:/var/run/
      - ../crypto-config/peerOrganizations/org2.demo.com/peers/peer1.org2.demo.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org2.demo.com/peers/peer1.org2.demo.com/tls:/etc/hyperledger/fabric/tls
  #      - ../crypto-config/peerOrganizations/demo.com/tlsca:/etc/hyperledger/orgs/peer1.org1.demo.com/tlsca

#  cli:
#    dns_search: .
#    container_name: cli
#    image: hyperledger/fabric-tools:1.4.4
#    tty: true
#    stdin_open: true
#    environment:
#      - SYS_CHANNEL=$SYS_CHANNEL
#      - GOPATH=/opt/gopath
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      #- FABRIC_LOGGING_SPEC=DEBUG
#      - FABRIC_LOGGING_SPEC=INFO
#      - CORE_PEER_ID=cli
#      - CORE_PEER_ADDRESS=peer0.org1.demo.com:8051
#      - CORE_PEER_LOCALMSPID=Org1MSP
#      - CORE_PEER_TLS_ENABLED=true
#      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.demo.com/peers/peer0.org1.demo.com/tls/server.crt
#      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.demo.com/peers/peer0.org1.demo.com/tls/server.key
#      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.demo.com/peers/peer0.org1.demo.com/tls/ca.crt
#      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.demo.com/users/Admin@org1.demo.com/msp
#    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    command: /bin/bash
#    volumes:
#      - /var/run/:/host/var/run/
#      #        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
#      - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
#      #        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
#      - ../artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/artifacts
#    depends_on:
#      - orderer.demo.com
#      - Org1Peer0
#      - Org1Peer1
networks:
  order-raft:
    driver: bridge