/*
# -*- coding: utf-8 -*-
# @Author : joker
# @Time : 2019-12-18 15:10 
# @File : tx_desc.go
# @Description : 
# @Attention : 
*/
package txbase

const (
	// USERCC_TX_BASE_USER_UPLOAD = base.TX_BASE_NEED_RECORD<<1 | base.TX_BASE_NEED_RECORD
	//
	// USERCC_TX_BASE_UPDATE_USERINFO = USERCC_TX_BASE_USER_UPLOAD << 1
	//
	// USERCC_TX_BASE_GET_USERINFO = USERCC_TX_BASE_USER_UPLOAD << 2| base.TX_BASE_UNNEED_RECORD
	//
	// USERCC_TX_BASE_GET_USERCOIN = USERCC_TX_BASE_GET_USERINFO << 1
	//
	// USERCC_TX_BASE_GET_USERWALLET=USERCC_TX_BASE_GET_USERCOIN<<1
)
