# ca-order 服务器,用于控制orderer节点
version: '2'
networks:
  ca:
services:
  order.ca:
    container_name: orderer.ca.${DOMAIN}
    image: hyperledger/fabric-ca:1.4.4
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-order
      - FABRIC_CA_SERVER_CSR_HOSTS=order.ca.demo.com
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ${GOPATH}/src/${DIRECTORY_NAME}/parent/crypto-config/caOrganizations/order-ca:/tmp/hyperledger/fabric-ca
    ports:
      - 3053:7054
    networks:
      ca:



  order.ca.child:
    container_name: orderer.ca.child.${DOMAIN}
    image: hyperledger/fabric-ca:1.4.4
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw -u https://admin:adminpw@order.ca.demo.com:3053 --intermediate.tls.certfiles /etc/hyperledger/crypto-config/caOrganizations/order-ca/ca-cert.pem '
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
#      - FABRIC_CA_SERVER_CSR_CN=ca-order
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ${GOPATH}/src/${DIRECTORY_NAME}/crypto-config/caOrganizations/order-ca:/tmp/hyperledger/fabric-ca
      - ${GOPATH}/src/${DIRECTORY_NAME}/parent/crypto-config/caOrganizations:/etc/hyperledger/crypto-config/caOrganizations
    extra_hosts:
      - "order.ca.demo.com:172.224.2.2"
    depends_on:
      - order.ca
    ports:
      - 4053:7054
    networks:
      ca: