# ca-tls 服务器,用于控制所有的组织之间的交流
version: '2'

networks:
  ca:
services:
  org.ca:
    container_name: org.ca.${DOMAIN}
    image: hyperledger/fabric-ca:1.4.4
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-demo
      - FABRIC_CA_SERVER_CSR_HOSTS=org.ca.demo.com
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ${GOPATH}/src/${DIRECTORY_NAME}/parent/crypto-config/caOrganizations/org-ca:/tmp/hyperledger/fabric-ca
    ports:
      - 3054:7054
    networks:
      ca:
        
        
  org.ca.child:
    container_name: org.ca.child.${DOMAIN}
    image: hyperledger/fabric-ca:1.4.4
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw -u https://admin:adminpw@org.ca.demo.com:3054 --intermediate.tls.certfiles /etc/hyperledger/crypto-config/caOrganizations/org-ca/ca-cert.pem'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ${GOPATH}/src/${DIRECTORY_NAME}/crypto-config/caOrganizations/org-ca:/tmp/hyperledger/fabric-ca
      - ${GOPATH}/src/${DIRECTORY_NAME}/parent/crypto-config/caOrganizations:/etc/hyperledger/crypto-config/caOrganizations
    ports:
      - 4054:7054
    extra_hosts:
      - "org.ca.demo.com:172.224.2.2"
    depends_on:
      - org.ca
    networks:
      ca:





