NodeOUs:
     Enable: true
     ClientOUIdentifier:
       Certificate: cacerts/0-0-0-0-4054.pem
       OrganizationalUnitIdentifier: client
     PeerOUIdentifier:
       Certificate: cacerts/0-0-0-0-4054.pem
       OrganizationalUnitIdentifier: peer
     AdminOUIdentifier:
       Certificate: cacerts/0-0-0-0-4054.pem
       OrganizationalUnitIdentifier: admin
     OrdererOUIdentifier:
       Certificate: cacerts/0-0-0-0-4054.pem
       OrganizationalUnitIdentifier: orderer 
