OrdererOrgs:
  - Name: Orderer
    Domain: demo.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: org1
    Domain: org1.com
    EnableNodeOUs: true
    Specs:
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: org2
    Domain: org2.com
    EnableNodeOUs: true
    Specs:
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: org3
    Domain: org3.com
    EnableNodeOUs: true
    Specs:
    Template:
      Count: 2
    Users:
      Count: 1


  - Name: org4
    Domain: org4.com
    EnableNodeOUs: true
    Specs:
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: org5
    Domain: org5.com
    EnableNodeOUs: true
    Specs:
    Template:
      Count: 2
    Users:
      Count: 1
