NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: 1/cacerts/ca.org0.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: 1/cacerts/ca.org0.com-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: 1/cacerts/ca.org0.com-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: 1/cacerts/ca.org0.com-cert.pem
    OrganizationalUnitIdentifier: orderer
