version: '2'
networks:
  demo:
services:
  
  
  peer0.org0.com:
    container_name: peer0.org0.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org0.com
      - CORE_PEER_ADDRESS=peer0.org0.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org0.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org0.com:10061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org0.com:10051
      - CORE_PEER_LOCALMSPID=Org0MSP
    ports:
      - "10051:10051"
      - "10052:10052"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.com/peers/peer0.org0.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org0.com/peers/peer0.org0.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  peer1.org0.com:
    container_name: peer1.org0.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org0.com
      - CORE_PEER_ADDRESS=peer1.org0.com:10061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10061
      - CORE_PEER_CHAINCODEADDRESS=peer1.org0.com:10062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org0.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org0.com:10061
      - CORE_PEER_LOCALMSPID=Org0MSP
    ports:
      - "10061:10061"
      - "10062:10062"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.com/peers/peer1.org0.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org0.com/peers/peer1.org0.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  
  
  peer0.org1.com:
    container_name: peer0.org1.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.com
      - CORE_PEER_ADDRESS=peer0.org1.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.com:11061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.com:11051
      - CORE_PEER_LOCALMSPID=Org1MSP
    ports:
      - "11051:11051"
      - "11052:11052"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  peer1.org1.com:
    container_name: peer1.org1.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.com
      - CORE_PEER_ADDRESS=peer1.org1.com:11061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11061
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.com:11062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.com:11061
      - CORE_PEER_LOCALMSPID=Org1MSP
    ports:
      - "11061:11061"
      - "11062:11062"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.com/peers/peer1.org1.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.com/peers/peer1.org1.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  
  
  peer0.org2.com:
    container_name: peer0.org2.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.com
      - CORE_PEER_ADDRESS=peer0.org2.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.com:12061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.com:12051
      - CORE_PEER_LOCALMSPID=Org2MSP
    ports:
      - "12051:12051"
      - "12052:12052"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  peer1.org2.com:
    container_name: peer1.org2.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.com
      - CORE_PEER_ADDRESS=peer1.org2.com:12061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12061
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.com:12062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.com:12061
      - CORE_PEER_LOCALMSPID=Org2MSP
    ports:
      - "12061:12061"
      - "12062:12062"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.com/peers/peer1.org2.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.com/peers/peer1.org2.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  
  
  peer0.org3.com:
    container_name: peer0.org3.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.com
      - CORE_PEER_ADDRESS=peer0.org3.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.com:13061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.com:13051
      - CORE_PEER_LOCALMSPID=Org3MSP
    ports:
      - "13051:13051"
      - "13052:13052"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org3.com/peers/peer0.org3.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org3.com/peers/peer0.org3.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  peer1.org3.com:
    container_name: peer1.org3.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.com
      - CORE_PEER_ADDRESS=peer1.org3.com:13061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13061
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.com:13062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.com:13061
      - CORE_PEER_LOCALMSPID=Org3MSP
    ports:
      - "13061:13061"
      - "13062:13062"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org3.com/peers/peer1.org3.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org3.com/peers/peer1.org3.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  
  
  peer0.org4.com:
    container_name: peer0.org4.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org4.com
      - CORE_PEER_ADDRESS=peer0.org4.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org4.com:14061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.com:14051
      - CORE_PEER_LOCALMSPID=Org4MSP
    ports:
      - "14051:14051"
      - "14052:14052"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org4.com/peers/peer0.org4.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org4.com/peers/peer0.org4.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  peer1.org4.com:
    container_name: peer1.org4.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org4.com
      - CORE_PEER_ADDRESS=peer1.org4.com:14061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14061
      - CORE_PEER_CHAINCODEADDRESS=peer1.org4.com:14062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org4.com:14061
      - CORE_PEER_LOCALMSPID=Org4MSP
    ports:
      - "14061:14061"
      - "14062:14062"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org4.com/peers/peer1.org4.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org4.com/peers/peer1.org4.com/tls:/etc/hyperledger/fabric/tls
    #      - /tmp/hyperledger/production/peer0:/var/hyperledger/production
    networks:
      demo:
  
  
  


  cli:
    container_name: cli
    image: jokerlvccc/fabric-tools:1.4.4
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=sysdemochannel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.com:11051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/fabric/msp
      - DEBUG_WARNING_LOGGABLE=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincodes:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - ./crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com/tls:/var/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/msp:/var/hyperledger/fabric/msp
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/artifacts
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    networks:
      demo:
    extra_hosts:
      
      
      - "peer0.org0.com:172.224.2.2"
      
      - "peer1.org0.com:172.224.2.2"
      
      
      
      - "peer0.org1.com:172.224.2.2"
      
      - "peer1.org1.com:172.224.2.2"
      
      
      
      - "peer0.org2.com:172.224.2.2"
      
      - "peer1.org2.com:172.224.2.2"
      
      
      
      - "peer0.org3.com:172.224.2.2"
      
      - "peer1.org3.com:172.224.2.2"
      
      
      
      - "peer0.org4.com:172.224.2.2"
      
      - "peer1.org4.com:172.224.2.2"
      
      
      - "orderer.demo.com:172.224.2.2"
      - "orderer1.demo.com:172.224.2.2"
      - "orderer2.demo.com:172.224.2.2"
      - "orderer3.demo.com:172.224.2.2"
      - "orderer4.demo.com:172.224.2.2"