version: '2'
networks:
  bidsun:
services:
  orderer:
    container_name: orderer.${DOMAIN}
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    ports:
      - "7050:7050"
    volumes:
      - ./channel-artifacts:/var/hyperledger/configtx
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer.${DOMAIN}/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer.${DOMAIN}/tls:/var/hyperledger/orderer/tls
#      - ./crypto-config/ordererOrganizations/${DOMAIN}/tlsca:/var/hyperledger/tlsca
#      - /tmp/hyperledger/production/orderer:/var/hyperledger/production
    networks:
      bidsun:



  orderer2:
    container_name: orderer2.${DOMAIN}
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    ports:
      - "5052:7050"
    volumes:
      - ./channel-artifacts:/var/hyperledger/configtx
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer2.${DOMAIN}/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer2.${DOMAIN}/tls:/var/hyperledger/orderer/tls
#      - ./crypto-config/ordererOrganizations/${DOMAIN}/tlsca:/var/hyperledger/tlsca
#      - /tmp/hyperledger/production/orderer2:/var/hyperledger/production
    networks:
      bidsun:
  orderer3:
    container_name: orderer3.${DOMAIN}
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    ports:
      - "5053:7050"
    volumes:
      - ./channel-artifacts:/var/hyperledger/configtx
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer3.${DOMAIN}/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer3.${DOMAIN}/tls:/var/hyperledger/orderer/tls
#      - ./crypto-config/ordererOrganizations/${DOMAIN}/tlsca:/var/hyperledger/tlsca
#      - /tmp/hyperledger/production/orderer3:/var/hyperledger/production
    networks:
      bidsun:
  orderer4:
    container_name: orderer4.${DOMAIN}
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    ports:
      - "5054:7050"
    volumes:
      - ./channel-artifacts:/var/hyperledger/configtx
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer4.${DOMAIN}/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer4.${DOMAIN}/tls:/var/hyperledger/orderer/tls
#      - ./crypto-config/ordererOrganizations/${DOMAIN}/tlsca:/var/hyperledger/tlsca
#      - /tmp/hyperledger/production/orderer4:/var/hyperledger/production
    networks:
      bidsun:
  orderer5:
    container_name: orderer5.${DOMAIN}
    extends:
      file: ./base/peer-base.yaml
      service: orderer-base
    ports:
      - "5055:7050"
    volumes:
      - ./channel-artifacts:/var/hyperledger/configtx
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer5.${DOMAIN}/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer5.${DOMAIN}/tls:/var/hyperledger/orderer/tls
    #      - ./crypto-config/ordererOrganizations/${DOMAIN}/tlsca:/var/hyperledger/tlsca
    #      - /tmp/hyperledger/production/orderer1:/var/hyperledger/production
    networks:
      bidsun:
