# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  bidchain:

services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=bidchain-sys-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.${DOMAIN}:7051
      - CORE_PEER_LOCALMSPID=BidsunMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/fabric/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincodes:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - ./crypto-config/peerOrganizations/${DOMAIN}/peers/peer1.${DOMAIN}/tls:/var/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/${DOMAIN}/users/Admin@bidsun.com/msp:/var/hyperledger/fabric/msp
      - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers:/var/hyperledger/fabric/orderers/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/artifacts
    networks:
      bidchain:
    extra_hosts:
      - "orderer.bidsun.com:172.224.2.2"
      - "orderer5.bidsun.com:172.224.2.2"
      - "orderer2.bidsun.com:172.224.2.2"
      - "orderer3.bidsun.com:172.224.2.2"
      - "orderer4.bidsun.com:172.224.2.2"

