NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: 4/cacerts/ca.org2.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: 4/cacerts/ca.org2.com-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: 4/cacerts/ca.org2.com-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: 4/cacerts/ca.org2.com-cert.pem
    OrganizationalUnitIdentifier: orderer
