NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: 2/cacerts/ca.demo.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: 2/cacerts/ca.demo.com-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: 2/cacerts/ca.demo.com-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: 2/cacerts/ca.demo.com-cert.pem
    OrganizationalUnitIdentifier: orderer
