# ca-order 服务器,用于控制orderer节点
version: '2'
networks:
  ca:
services:
  order.ca:
    container_name: orderer.ca.${DOMAIN}
    image: hyperledger/fabric-ca:1.4.2
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-order
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ${GOPATH}/src/${DIRECTORY_NAME}/crypto-config/caOrganizations/order-ca:/tmp/hyperledger/fabric-ca
    ports:
      - 4053:7054
    networks:
      ca: