# ca-tls 服务器,用于控制所有的组织之间的交流
version: '2'
networks:
  ca:
services:
  tls.ca:
    container_name: tls.ca.${DOMAIN}
    image: hyperledger/fabric-ca:1.4.4
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw '
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-tls
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ${GOPATH}/src/${DIRECTORY_NAME}/crypto-config/caOrganizations/tls-ca:/tmp/hyperledger/fabric-ca
    ports:
      - 4052:7054
    networks:
      ca: