sql:
  extention:
    config-table-counts: 1
    table-names: user
    detail-config: 2:userSQLExtentionProxy:2=user_0,user_1;2=user_0,user_1
    #    detail-config: 2:categorySQLExtentionProxyDaoImpl:1=tmall_category_0;1=tmall_category_0-2:messageSQLExtentionDaoImpl:1=message_0;1=message_0
    